### PR TITLE
resolved improper filepath concatenation in kilosort processing methods.

### PR DESCRIPTION
**Pull request by gvoysey**
I replaced all instances of the pattern `fileLocation = [rootPath 'file_name.extension']`, which does not insert `filesep()` between items, with calls to `fullfile()`, which does.

In the cases where the same path is used multiple times (e.g., in an existence test and also as a load), I've made that location a variable that's called multiple times, which avoids typo and cut-and-paste errors.

I did not change anything in the `+sqKwik` directory because I don't have anything to test against -- however, please note that the value of `filesep()` is OS-dependent, and matlab will not always resolve paths correctly if the file separator is hard-coded.

### CODE REVIEW

**Comment by nsteinme** [comment]
excellent, thank you!

**Comment by gvoysey** [comment]
happy to help! expect some more stuff from me and @rswilliamson -- we'll be using kilosort heavily starting this week.

**Comment by nsteinme** [comment]
Great! Kilosort is amazing, I'm sure you'll be happy with it. These sorting
quality functions, don't get such high expectations ;)

**Comment by gvoysey** [comment]
I'll keep that in mind :wink: 

we'll have heaps of data to test them on, though!

**Pull request merged**
